// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnkxdpkvhvmnrbomjsij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRua3hkcGt2aHZtbnJib21qc2lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODQwNTYsImV4cCI6MjA2NTQ2MDA1Nn0.VTiXbg7aeN6ltFEjOnq6i6CwYMdnfWfVTMfbCjr2660";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);